### ISSUE TITLE
Test dependency updates

### ISSUE THREAD

**Issue by earthgecko** [earthgecko/skyline#23]
Dependency updates to be tested with Python-2.7.12

scipy==0.17.1 to scipy==0.18.0
pytz==2016.4 to pytz==2016.6.1
pyparsing==2.1.5 to pyparsing==2.1.8
matplotlib==1.5.1 to matplotlib==1.5.2
msgpack-python==0.4.7 to msgpack-python==0.4.8
requests==2.10.0 to requests==2.11.1

**Comment by earthgecko** [comment]
There was an issue with matplotlib==1.5.2 but the others are all fine.

```
2016-08-20 12:20:44 :: 1942 :: error :: alert_smtp - could not build plot
2016-08-20 12:20:44 :: 1942 :: Traceback (most recent call last):
  File "/opt/skyline/github/skyline/skyline/mirage/mirage_alerters.py", line 248, in alert_smtp
    fig = plt.figure(frameon=False)
  File "/opt/python_virtualenv/projects/skyline-py2712/lib/python2.7/site-packages/matplotlib/pyplot.py", line 527, in figure
    **kwargs)
  File "/opt/python_virtualenv/projects/skyline-py2712/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 84, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/opt/python_virtualenv/projects/skyline-py2712/lib/python2.7/site-packages/matplotlib/backends/backend_tkagg.py", line 92, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/opt/python_virtualenv/versions/2.7.12/lib/python2.7/lib-tk/Tkinter.py", line 1815, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
TclError: no display name and no $DISPLAY environment variable

2016-08-20 12:20:45
```

This required an additional matplotlib call in alerters as matplotlib==1.5.2 requries an additional configuration defined of matplotlib.use('Agg') for the the generation of a plot in a non windowed environment.

All tested and working as desired.
